### ISSUE TITLE
No Trailers

### ISSUE THREAD

**Issue by nunavailabul** [kzeleny/screensaver.randomtrailers#2]
Set to default values, also tried disabling itunes.  

Addon plays the intro then you just get error popup - see log file.

Running on Ubuntu 18.04
Kodi V 17.6
Addon installed from kodi repo

` ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno -2] Name or service not known>
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/screensaver.randomtrailers/default.py", line 979, in <module>
                                                iTunes_trailers = getItunesTrailers()
                                              File "/home/kodi/.kodi/addons/screensaver.randomtrailers/default.py", line 281, in getItunesTrailers
                                                if trailer_type == 4:content = opener.open(urlMain+"/trailers/home/feeds/studios.json").read()
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
                                                return self.do_open(httplib.HTTPConnection, req)
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno -2] Name or service not known>
                                            -->End of Python script error report<--`

**Comment by nunavailabul** [comment]
last part of the error (urllib2 - opening the urls) I think has to do with DNS and the changes in /etc/resolv.conf for more recent versions of ubuntu.

Changed the sym link for /etc/resolv.conf to `ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf`  to get DNS resolution (I'm aware this is a whole systemd/netplan scenario - i just wanted name resolution nao, which i got).

Remaining error then becomes:

`ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/screensaver.randomtrailers/default.py", line 979, in <module>
                                                iTunes_trailers = getItunesTrailers()
                                              File "/home/kodi/.kodi/addons/screensaver.randomtrailers/default.py", line 316, in getItunesTrailers
                                                director = match[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--`

**Comment by nunavailabul** [comment]
With iTunes option disabled in settings, this is the error:

`ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Non-Existent Control 30001
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/screensaver.randomtrailers/default.py", line 711, in onInit
                                                self.getControl(30001).setImage(trailer["thumbnail"])
                                            RuntimeError: Non-Existent Control 30001
                                            -->End of Python script error report<--`
